name: flutter_highlight_gallery
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_highlighting:
    path: ../
  highlighting:
    path: ../../highlighting

dev_dependencies:
  total_lints: ^3.4.0

flutter:
  uses-material-design: true

dependency_overrides:
  highlighting:
    path: ../../highlighting
