// GENERATED CODE - DO NOT MODIFY BY HAND

// ignore_for_file: file_names

import 'package:flutter/painting.dart';

const cybertopiaDimmerTheme = {
  'root': TextStyle(
    color: Color(0xffabb2bf),
    backgroundColor: Color(0xff101010),
  ),
  'comment': TextStyle(color: Color(0xff5c6370), fontStyle: FontStyle.italic),
  'quote': TextStyle(color: Color(0xff5c6370), fontStyle: FontStyle.italic),
  'code': TextStyle(color: Color(0xff5c6370), fontStyle: FontStyle.italic),
  'doctag': TextStyle(color: Color(0xffa246be)),
  'keyword': TextStyle(color: Color(0xffa246be)),
  'formula': TextStyle(color: Color(0xffa246be)),
  'section': TextStyle(color: Color(0xffc50233)),
  'name': TextStyle(color: Color(0xffc50233)),
  'selector-tag': TextStyle(color: Color(0xffc50233)),
  'deletion': TextStyle(color: Color(0xffc50233)),
  'subst': TextStyle(color: Color(0xffc50233)),
  'literal': TextStyle(color: Color(0xff97c502)),
  'string': TextStyle(color: Color(0xff02c797)),
  'regexp': TextStyle(color: Color(0xff02c797)),
  'addition': TextStyle(color: Color(0xff02c797)),
  'attribute': TextStyle(color: Color(0xff02c797)),
  'attr': TextStyle(color: Color(0xffbe6446)),
  'variable': TextStyle(color: Color(0xffbe6446)),
  'template-variable': TextStyle(color: Color(0xffbe6446)),
  'type': TextStyle(color: Color(0xffbe6446)),
  'selector-class': TextStyle(color: Color(0xffbe6446)),
  'selector-attr': TextStyle(color: Color(0xffbe6446)),
  'selector-pseudo': TextStyle(color: Color(0xffbe6446)),
  'number': TextStyle(color: Color(0xffbe6446)),
  'punctuation': TextStyle(color: Color(0xffbe6446)),
  'variable.language_': TextStyle(color: Color(0xffbe6446)),
  'symbol': TextStyle(color: Color(0xff469ebe)),
  'bullet': TextStyle(color: Color(0xff469ebe)),
  'link': TextStyle(
    color: Color(0xff469ebe),
    decoration: TextDecoration.underline,
  ),
  'meta': TextStyle(color: Color(0xff469ebe)),
  'selector-id': TextStyle(color: Color(0xff469ebe)),
  'title': TextStyle(color: Color(0xff469ebe)),
  'title.function_': TextStyle(color: Color(0xff469ebe)),
  'property': TextStyle(color: Color(0xff469ebe)),
  'tag': TextStyle(color: Color(0xff469ebe)),
  'char.escape_': TextStyle(color: Color(0xff469ebe)),
  'built_in': TextStyle(color: Color(0xffc5bb02)),
  'title.class_': TextStyle(color: Color(0xffc5bb02)),
  'title.class_.inherited__': TextStyle(color: Color(0xffc5bb02)),
  'emphasis': TextStyle(fontStyle: FontStyle.italic),
  'strong': TextStyle(fontWeight: FontWeight.bold),
  'params': TextStyle(color: Color(0xff64be46)),
  'operator': TextStyle(color: Color(0xff64be46)),
  'template-tag': TextStyle(color: Color(0xff64be46)),
};
