name: flutter_highlighting
description: Syntax highlighting widget for Flutter with lots of languages and themes support.
version: 0.9.1+11.8.0
publish_to: "none"
homepage: https://github.com/akvelon/dart-highlighting

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter: { sdk: flutter }
  highlighting:
    git:
      url: https://github.com/poppingmoon/dart-highlighting
      ref: cabd93636e331707ad6ff0f548a9c21e07b0e6c7
      path: highlighting

dev_dependencies:
  total_lints: ^3.4.0

dependency_overrides:
  highlighting:
    path: ../highlighting
